apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/samdoran/ubi-trino?rev={{ revision }}
    build.appstudio.redhat.com/commit_sha: '{{ revision }}'
    build.appstudio.redhat.com/target_branch: '{{ target_branch }}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "test"
  creationTimestamp: null

  labels:
    appstudio.openshift.io/application: test
    appstudio.openshift.io/component: test
    pipelines.appstudio.openshift.io/type: build

  namespace: cost-mgmt-dev-tenant
  name: test-push

spec:
  params:
    - name: git-url
      value: '{{ source_url }}'

    - name: revision
      value: '{{ revision }}'

    - name: output-image
      value: quay.io/redhat-user-workloads/cost-mgmt-dev-tenant/test:{{ revision }}

    - name: dockerfile
      value: Dockerfile

    - name: path-context
      value: .

  pipelineRef:
    name: pipeline-build-multiarch

  taskRunSpecs:
    - pipelineTaskName: clamav-scan
      stepOverrides:
        - name: extract-and-scan-image
          computeResources:
            requests:
              cpu: 1500m
              memory: 4Gi

    - pipelineTaskName: ecosystem-cert-preflight-checks
      computeResources:
        requests:
          memory: 1Gi

  timeouts:
    tasks: 2h

  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
